### ISSUE TITLE
terraform import no longer works

### ISSUE THREAD

**Issue by paulca99** [Mongey/terraform-provider-kafka#100]
Hi, We're on terraform 0.12 and have a major issue breaking our disaster recovery process.  Once using the terraform-provider-kafka , we can plan and apply no problem. BUT when attempting to import a restored EFS drive we get:-

$ terraform import aws_efs_file_system.Research-nginx-efs-perm-store fs-4d5d0086
aws_efs_file_system.Research-nginx-efs-perm-store: Importing from ID "fs-4d5d0086"...
aws_efs_file_system.Research-nginx-efs-perm-store: Import prepared!
  Prepared aws_efs_file_system for import
aws_efs_file_system.Research-nginx-efs-perm-store: Refreshing state... [id=fs-4d5d0086]

**Error: Missing required argument

The argument "bootstrap_servers" is required, but was not set.**

And the import fails.  Any ideas ?

**Comment by paulca99** [comment]
Can't stress how important this is to us , We're now running with inconsistent state as our restored drives aren't linked to the terraform state, so we can't run terraform apply anymore as it will create a new empty drive, and mount that on our EC2 instances instead of the real drive with the data.

**Comment by Mongey** [comment]
I suspect this is a duplicate of #95. I'll try get some time to look into this. Perhaps something changed with terraform 0.12.

**Comment by paulca99** [comment]
unlike #95 this is importing something completely unrelated to kafka ..... an EFS drive. I even tried defining bootstrap_server as a var and auto.tfvar , and passing it on the command line with -var ........ same error .  The only way I can see us getting our TF state back in sync at the moment is to manually strip all the kafka resources out of the state . .... painful..... hoping you can spot the error quickly.

**Comment by Mongey** [comment]
Can you share some of your tf config & the output of `TF_LOG=debug terraform import ...`
Probably best to encrypt it. https://keybase.io/encrypt#mongeyc

**Comment by paulca99** [comment]
Sorry Conor, was really trying not to sound like a drama queen.... but just re-read it and it does sound a bit "dramatic" .... to be clear.... prod is still up and running , just can't make any TF changes until we sort this, or unpick it.

**Comment by Mongey** [comment]
This should be fixed in 0.2.4 / 0.2.5

**Comment by jinbowang** [comment]
am still getting the same error under v0.2.5.
import worked once to me, and then it stopped working, same error, even I just remove the module completely. 

I assume its somewhere in tfstate file that looks for such information?
