### ISSUE TITLE
⚠️ Dependency Resolution Bug: kafka_user_scram_credential ignores password values from random_password resources

### ISSUE THREAD

**Issue by leva0887** [Mongey/terraform-provider-kafka#580]
## Problem
The `kafka_user_scram_credential` resource doesn't properly wait for `random_password` dependencies to be created before attempting to use the password value.

## Steps to reproduce
1. Create a `random_password` resource with `for_each`
2. Create a `kafka_user_scram_credential` resource that references `random_password[each.key].result`
3. Run `terraform plan` or `terraform apply`

## Expected behavior
The `kafka_user_scram_credential` should wait for `random_password` to be created before attempting to use the password.

## Actual behavior
│ Error: either 'password' or 'password_wo' must be specified

## Environment
- Terraform version: 1.12.2
- Kafka provider version: 0.11.0
- Kafka cluster version: 3.9

## Code example
```hcl
resource "random_password" "application_users" {
  for_each = { for user in var.users : user.name => user if user.create }

  length = 16
  # ... other settings
}

resource "kafka_user_scram_credential" "application_users" {
  for_each = { for user in var.users : user.name => user if user.create }

  username = each.key
  password = random_password.application_users[each.key].result
  # ... other settings
}
```

**Comment by Mongey** [comment]
@leva0887 can you try v0.13.0 ? it may have been fixed in https://github.com/Mongey/terraform-provider-kafka/pull/575

**Comment by thomasq0** [comment]
I don't think v0.13.0 resolved this issue.
> Using previously-installed hashicorp/aws v5.100.0
> Using previously-installed hashicorp/vault v4.7.0
> Using previously-installed hashicorp/random v3.7.2
> Using previously-installed mongey/kafka v0.13.0
...
> Stack trace from the terraform-provider-kafka_v0.13.0 plugin:
> panic: value is unknown

**Comment by bastienmenis** [comment]
I confirm this bug is still present with the latest version of the provider (0.13.1). Trying to create a `kafka_user_scram_credential` that depends on a `random_password` resource that does not exist yet causes the provider to crash at plan time.

**Comment by leva0887** [comment]
I created a PR please review it https://github.com/Mongey/terraform-provider-kafka/pull/639

**Comment by Planche95** [comment]
@Mongey do you know when new version with fix will be released?

**Comment by bcatubig-apex** [comment]
Hi @Mongey -- any chance we could cut a new release? I see this was merged to main back in Jan
