### ISSUE TITLE
Is your cluster reachable

### ISSUE THREAD

**Issue by MrMunki** [Mongey/terraform-provider-kafka#60]
I'm trying to use this plugin over in SSL auth config but I keep getting the above error. I've even tried it directly on the broker, but it still doesn't work. Am I missing something obvious?

Error: Error running plan: 1 error occurred:
        * provider.kafka: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

I'm using kafka 2.1.1 on centos 7 if that's at all helpful.

**Comment by Mongey** [comment]
Hey @MrMunki :wave:, can you share the config you're using to attempt to connect? 
Also, running `TF_LOG=debug terraform plan` might provide some more information into what's happening.

**Comment by MrMunki** [comment]
Hi,

Thanks for the response. I've just tried against an unencrypted kafka cluster and it does work, so it's the certs causing the issue by the looks of it. I've looked in the authorizer logs on the kafka server but it does not appear in there so it seems it's not even attempting to connect to the server.

My provider config is below, I've also attached the error bit of the log. The server name, of course, is changed

provider "kafka" {
  bootstrap_servers = ["kafkabroker.domain.net:9093"]
  ca_cert_file      = "/folder/ca-cert"
  client_cert_file  = "/folder/kafka_cert"
  client_key_file   = "/folder/kafka.key"
  skip_tls_verify   = false
  tls_enabled       = true
}

[TF_kafka_log.txt](https://github.com/Mongey/terraform-provider-kafka/files/3410316/TF_kafka_log.txt)

**Comment by Mongey** [comment]
Can you try with  `skip_tls_verify = true` ... I wonder if something there is broken 😅

**Comment by MrMunki** [comment]
I already tried that, and I've just tried it again, and no joy, still the same.

**Comment by MrMunki** [comment]
Hi, have you had a chance to look at this again?

**Comment by diodonfrost** [comment]
Same problem here

**Comment by kdefives** [comment]
Same issue here with 
`skip_tls_verify   = true`
`tls_enabled       = false`

**Comment by rajivchirania** [comment]
Has anyone able to find solution for Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)  for AWS MSK

**Comment by Mongey** [comment]
Alright, I believer there was an issue with how the CA chain was being set. This should be resolved in the latest release.

**Comment by MrMunki** [comment]
Still getting the same error

Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

**Comment by mleuthold** [comment]
I'm having the same issue as @MrMunki . 

### This is the code I'm using:

provider "kafka" {
  bootstrap_servers = [
    "kafka-1.my.domain:9091",
    "kafka-2.my.domain:9091",
    "kafka-3.my.domain:9091",
    "kafka-4.my.domain:9091",
    "kafka-5.my.domain:9091",
    "kafka-6.my.domain:9091",
  ] #["kafka.my.domain:9091"]
  skip_tls_verify   = true
}

resource "kafka_topic" "progression_rate" {
  name               = "systemd_logs"
  replication_factor = 2
  partitions         = 6
}

### This is the output:

terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

  on main.tf line 1, in provider "kafka":
   1: provider "kafka" {

Versions in use are:

terraform-provider-kafka: v0.2.3
terraform: v0.12.20

**Comment by mleuthold** [comment]
@MrMunki I had the same issue as you, but I used the wrong port in combination with the wrong config. These are the configs which work for me.

For port 9091 I use
  skip_tls_verify   = true
  tls_enabled = false

For port 9092 I use
  skip_tls_verify   = true
  tls_enabled = true

AFAIK 9092 is the SSL port of Kafka.

**Comment by MrMunki** [comment]
@mleuthold 
Hi, the SSL port is 9093, I believe. 9092 is not even listening on my cluster as I have to have encryption.
